
name: CI
on:
  push:
  pull_request:

# Least privilege: only read contents. (Additional scopes can be added per job if needed.)
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    # No write permissions required for standard CI
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Ruff auto-fix (imports & simple style)
        run: ruff check . --fix --exit-zero
      - name: Ruff (lint)
        run: ruff check .
      - name: Mypy (type check)
        run: mypy src
      - name: Pytest
        run: pytest
      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0 pinned
        with:
          files: coverage.xml
          fail_ci_if_error: true
          verbose: false
      - name: Show coverage summary
        if: always()
        run: |
          if [ -f coverage.xml ]; then grep -E 'line-rate' coverage.xml || true; fi
      # - name: Upload coverage artifact (optional)
      #   uses: actions/upload-artifact@<pin-sha>
      #   with:
      #     name: coverage-xml
      #     path: coverage.xml
