
name: CI
on:
  push:
  pull_request:
permissions:
  contents: read
  actions: read
  checks: read
  security-events: write  # only for SARIF upload steps if used
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Lint
        run: ruff check .
      - name: Type check
        run: mypy src
      - name: Test
        run: pytest
